version: 2.1

jobs:
  build:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - run:
          name: Install Fastlane and run scan
          command: |
            gem install fastlane
            fastlane scan
    timeouts:
      build: 1800

workflows:
  sample:
    jobs:
      - build
