version: 2.1

jobs:
  build:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - run: 
          name: Fastlane
          command: |
            export FASTLANE_XCODEBUILD_SETTINGS_RETRIES=8
            export FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT=120
            fastlane scan

workflows:
  sample:
    jobs:
      - build
