version: 2.1

jobs:
  build:
    macos:
      xcode: 14.0.1
    environment:
      FASTLANE_XCODE_LIST_TIMEOUT: 300
    steps:
      - checkout
      - run: 
          name: Fastlane
          command: |
            fastlane scan
          no_output_timeout: 60m

workflows:
  sample:
    jobs:
      - build
