version: 2.1

jobs:
  build:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: |
            gem install cocoapods
            pod install
      - run: fastlane scan

workflows:
  sample:
    jobs:
      - build
